# Generated by Django 4.2.3 on 2023-07-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='articles',
            name='date_edited',
            field=models.DateTimeField(default='None', verbose_name='Отредактировано'),
        ),
    ]
