# Generated by Django 4.2.3 on 2023-07-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_articles_date_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='date_edited',
        ),
    ]
